### ISSUE TITLE
stage I

### ISSUE THREAD

**Issue by rusdevops** [lightman1998/HomeWork_01#2]
Обсуждали сегодня на занятии
https://github.com/lightman1998/HomeWork_01/blob/7b915e973ee9480fc8d0f738ef5314eb15121825/stack.h#L1-L2
Обсуждали сегодня на занятии
https://github.com/lightman1998/HomeWork_01/blob/7b915e973ee9480fc8d0f738ef5314eb15121825/stack.h#L17-L27
Обсуждали сегодня на занятии
https://github.com/lightman1998/HomeWork_01/blob/7b915e973ee9480fc8d0f738ef5314eb15121825/stack.h#L45
Некорректная работа с массивом
https://github.com/lightman1998/HomeWork_01/blob/7b915e973ee9480fc8d0f738ef5314eb15121825/stack.h#L20

**Comment by lightman1998** [comment]
Все переделал
